from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "cli",
    "config",
    "contracts",
    "crypto",
    "data_stooq",
    "data_yf",
    "extended_hours_monitor",
    "fx",
    "intraday_live",
    "intraday_research",
    "parquet_verify",
    "schema",
    "store_report",
    "symbol_master",
    "ticker_map",
    "universe",
    "universe_build",
    "workflows",
    "ARTIFACT_SCHEMA_VERSION",
    "ArtifactFamilyEntry",
    "CompatibilityManifest",
    "ConfigLike",
    "CoverageEntry",
    "CryptoMetadataEntry",
    "CryptoRegistryEntry",
    "CryptoSyncResult",
    "CryptoUniverseRefreshResult",
    "CryptoValidateResult",
    "DailyCloseInfo",
    "ExchangeDefaultEntry",
    "ExtendedHoursResult",
    "FxDailyEntry",
    "FxSyncResult",
    "FxValidateResult",
    "IntradayDualSyncResult",
    "IntradayLiveSyncResult",
    "IntradayLiveValidateResult",
    "IntradayResearchSyncResult",
    "IntradayResearchValidateResult",
    "MonitorExtendedHoursResult",
    "StoreHistoryEntry",
    "StoreIntegrityFileIssue",
    "StoreIntegrityReport",
    "StoreIntegritySection",
    "SymbolMasterBuildResult",
    "SymbolMasterEntry",
    "SymbolMasterValidateResult",
    "SymbolOverrideEntry",
    "UpdateResult",
    "VerifyResult",
    "UniverseRow",
    "available_fx_pairs",
    "backfill_extended_hours_from_config",
    "build_symbol_master_frame",
    "build_universe",
    "canonicalize_symbol",
    "clear_currency_cache",
    "clear_override_cache",
    "compatibility_manifest",
    "crypto_backfill_from_config",
    "crypto_diff_universe_from_config",
    "crypto_inspect_from_config",
    "crypto_list_symbols_from_config",
    "crypto_prune_from_config",
    "crypto_refresh_universe_from_config",
    "crypto_show_universe_from_config",
    "crypto_validate_from_config",
    "derive_inverse_fx_frame",
    "generate_parquet_store_report",
    "generate_universe_consistency_report",
    "identity_fx_frame",
    "inspect_symbol_master_frame",
    "intraday_live_inspect_from_config",
    "intraday_live_update_from_config",
    "intraday_live_validate_from_config",
    "intraday_research_inspect_from_config",
    "intraday_research_update_from_config",
    "intraday_research_validate_from_config",
    "intraday_sync_from_config",
    "load_exchange_defaults",
    "load_fx_pair",
    "load_symbol_master_frame",
    "load_symbol_master_map",
    "load_symbol_overrides",
    "load_universe",
    "load_universe_frame",
    "make_fx_pair_to_base",
    "monitor_extended_hours_from_config",
    "normalize_fx_pair",
    "normalize_to_yahoo",
    "render_schema_json",
    "render_schema_markdown",
    "render_universe_consistency_json",
    "render_universe_consistency_markdown",
    "run_parquet_sanity_checks",
    "schema_manifest",
    "sync_fx_pair_yahoo",
    "update_from_config",
    "validate_alerts_frame",
    "validate_crypto_frame",
    "validate_daily_frame",
    "validate_fx_daily_frame",
    "validate_fx_pair",
    "validate_intraday_frame",
    "validate_intraday_live_frame",
    "validate_intraday_research_frame",
    "validate_moves_frame",
    "validate_symbol_master",
    "validate_symbol_master_frame",
]

_LAZY_EXPORTS: dict[str, tuple[str, str | None]] = {
    "cli": ("tradinglab_data.cli", None),
    "config": ("tradinglab_data.config", None),
    "contracts": ("tradinglab_data.contracts", None),
    "crypto": ("tradinglab_data.crypto", None),
    "data_stooq": ("tradinglab_data.data_stooq", None),
    "data_yf": ("tradinglab_data.data_yf", None),
    "extended_hours_monitor": ("tradinglab_data.extended_hours_monitor", None),
    "fx": ("tradinglab_data.fx", None),
    "intraday_live": ("tradinglab_data.intraday_live", None),
    "intraday_research": ("tradinglab_data.intraday_research", None),
    "parquet_verify": ("tradinglab_data.parquet_verify", None),
    "schema": ("tradinglab_data.schema", None),
    "store_report": ("tradinglab_data.store_report", None),
    "symbol_master": ("tradinglab_data.symbol_master", None),
    "ticker_map": ("tradinglab_data.ticker_map", None),
    "universe": ("tradinglab_data.universe", None),
    "universe_build": ("tradinglab_data.universe_build", None),
    "workflows": ("tradinglab_data.workflows", None),
    "ARTIFACT_SCHEMA_VERSION": ("tradinglab_data.contracts", "ARTIFACT_SCHEMA_VERSION"),
    "ArtifactFamilyEntry": ("tradinglab_data.contracts", "ArtifactFamilyEntry"),
    "CompatibilityManifest": ("tradinglab_data.contracts", "CompatibilityManifest"),
    "ConfigLike": ("tradinglab_data.config", "ConfigLike"),
    "CoverageEntry": ("tradinglab_data.contracts", "CoverageEntry"),
    "CryptoMetadataEntry": ("tradinglab_data.contracts", "CryptoMetadataEntry"),
    "CryptoRegistryEntry": ("tradinglab_data.contracts", "CryptoRegistryEntry"),
    "CryptoSyncResult": ("tradinglab_data.contracts", "CryptoSyncResult"),
    "CryptoUniverseRefreshResult": ("tradinglab_data.contracts", "CryptoUniverseRefreshResult"),
    "CryptoValidateResult": ("tradinglab_data.contracts", "CryptoValidateResult"),
    "DailyCloseInfo": ("tradinglab_data.contracts", "DailyCloseInfo"),
    "ExchangeDefaultEntry": ("tradinglab_data.contracts", "ExchangeDefaultEntry"),
    "ExtendedHoursResult": ("tradinglab_data.contracts", "ExtendedHoursResult"),
    "FxDailyEntry": ("tradinglab_data.contracts", "FxDailyEntry"),
    "FxSyncResult": ("tradinglab_data.contracts", "FxSyncResult"),
    "FxValidateResult": ("tradinglab_data.contracts", "FxValidateResult"),
    "IntradayDualSyncResult": ("tradinglab_data.contracts", "IntradayDualSyncResult"),
    "IntradayLiveSyncResult": ("tradinglab_data.contracts", "IntradayLiveSyncResult"),
    "IntradayLiveValidateResult": ("tradinglab_data.contracts", "IntradayLiveValidateResult"),
    "IntradayResearchSyncResult": ("tradinglab_data.contracts", "IntradayResearchSyncResult"),
    "IntradayResearchValidateResult": ("tradinglab_data.contracts", "IntradayResearchValidateResult"),
    "MonitorExtendedHoursResult": ("tradinglab_data.contracts", "MonitorExtendedHoursResult"),
    "StoreHistoryEntry": ("tradinglab_data.contracts", "StoreHistoryEntry"),
    "StoreIntegrityFileIssue": ("tradinglab_data.contracts", "StoreIntegrityFileIssue"),
    "StoreIntegrityReport": ("tradinglab_data.contracts", "StoreIntegrityReport"),
    "StoreIntegritySection": ("tradinglab_data.contracts", "StoreIntegritySection"),
    "SymbolMasterBuildResult": ("tradinglab_data.contracts", "SymbolMasterBuildResult"),
    "SymbolMasterEntry": ("tradinglab_data.contracts", "SymbolMasterEntry"),
    "SymbolMasterValidateResult": ("tradinglab_data.contracts", "SymbolMasterValidateResult"),
    "SymbolOverrideEntry": ("tradinglab_data.contracts", "SymbolOverrideEntry"),
    "UpdateResult": ("tradinglab_data.contracts", "UpdateResult"),
    "VerifyResult": ("tradinglab_data.contracts", "VerifyResult"),
    "UniverseRow": ("tradinglab_data.universe_build", "UniverseRow"),
    "available_fx_pairs": ("tradinglab_data.fx", "available_fx_pairs"),
    "backfill_extended_hours_from_config": ("tradinglab_data.workflows", "backfill_extended_hours_from_config"),
    "build_symbol_master_frame": ("tradinglab_data.symbol_master", "build_symbol_master_frame"),
    "build_universe": ("tradinglab_data.universe_build", "build_universe"),
    "canonicalize_symbol": ("tradinglab_data.universe", "canonicalize_symbol"),
    "clear_currency_cache": ("tradinglab_data.data_yf", "clear_currency_cache"),
    "clear_override_cache": ("tradinglab_data.ticker_map", "clear_override_cache"),
    "compatibility_manifest": ("tradinglab_data.schema", "compatibility_manifest"),
    "crypto_backfill_from_config": ("tradinglab_data.crypto.workflows", "crypto_backfill_from_config"),
    "crypto_diff_universe_from_config": ("tradinglab_data.crypto.workflows", "crypto_diff_universe_from_config"),
    "crypto_inspect_from_config": ("tradinglab_data.crypto.workflows", "crypto_inspect_from_config"),
    "crypto_list_symbols_from_config": ("tradinglab_data.crypto.workflows", "crypto_list_symbols_from_config"),
    "crypto_prune_from_config": ("tradinglab_data.crypto.workflows", "crypto_prune_from_config"),
    "crypto_refresh_universe_from_config": ("tradinglab_data.crypto.workflows", "crypto_refresh_universe_from_config"),
    "crypto_show_universe_from_config": ("tradinglab_data.crypto.workflows", "crypto_show_universe_from_config"),
    "crypto_validate_from_config": ("tradinglab_data.crypto.workflows", "crypto_validate_from_config"),
    "derive_inverse_fx_frame": ("tradinglab_data.fx", "derive_inverse_fx_frame"),
    "generate_parquet_store_report": ("tradinglab_data.store_report", "generate_parquet_store_report"),
    "generate_universe_consistency_report": ("tradinglab_data.consistency_report", "generate_universe_consistency_report"),
    "identity_fx_frame": ("tradinglab_data.fx", "identity_fx_frame"),
    "inspect_symbol_master_frame": ("tradinglab_data.symbol_master", "inspect_symbol_master_frame"),
    "intraday_live_inspect_from_config": ("tradinglab_data.workflows", "intraday_live_inspect_from_config"),
    "intraday_live_update_from_config": ("tradinglab_data.workflows", "intraday_live_update_from_config"),
    "intraday_live_validate_from_config": ("tradinglab_data.workflows", "intraday_live_validate_from_config"),
    "intraday_research_inspect_from_config": ("tradinglab_data.workflows", "intraday_research_inspect_from_config"),
    "intraday_research_update_from_config": ("tradinglab_data.workflows", "intraday_research_update_from_config"),
    "intraday_research_validate_from_config": ("tradinglab_data.workflows", "intraday_research_validate_from_config"),
    "intraday_sync_from_config": ("tradinglab_data.workflows", "intraday_sync_from_config"),
    "load_exchange_defaults": ("tradinglab_data.symbol_master", "load_exchange_defaults"),
    "load_fx_pair": ("tradinglab_data.fx", "load_fx_pair"),
    "load_symbol_master_frame": ("tradinglab_data.symbol_master", "load_symbol_master_frame"),
    "load_symbol_master_map": ("tradinglab_data.symbol_master", "load_symbol_master_map"),
    "load_symbol_overrides": ("tradinglab_data.symbol_master", "load_symbol_overrides"),
    "load_universe": ("tradinglab_data.universe", "load_universe"),
    "load_universe_frame": ("tradinglab_data.universe", "load_universe_frame"),
    "make_fx_pair_to_base": ("tradinglab_data.symbol_master", "make_fx_pair_to_base"),
    "monitor_extended_hours_from_config": ("tradinglab_data.workflows", "monitor_extended_hours_from_config"),
    "normalize_fx_pair": ("tradinglab_data.symbol_master", "normalize_fx_pair"),
    "normalize_to_yahoo": ("tradinglab_data.ticker_map", "normalize_to_yahoo"),
    "render_schema_json": ("tradinglab_data.schema", "render_schema_json"),
    "render_schema_markdown": ("tradinglab_data.schema", "render_schema_markdown"),
    "render_universe_consistency_json": ("tradinglab_data.consistency_report", "render_universe_consistency_json"),
    "render_universe_consistency_markdown": ("tradinglab_data.consistency_report", "render_universe_consistency_markdown"),
    "run_parquet_sanity_checks": ("tradinglab_data.parquet_verify", "run_parquet_sanity_checks"),
    "schema_manifest": ("tradinglab_data.schema", "schema_manifest"),
    "sync_fx_pair_yahoo": ("tradinglab_data.fx", "sync_fx_pair_yahoo"),
    "update_from_config": ("tradinglab_data.workflows", "update_from_config"),
    "validate_alerts_frame": ("tradinglab_data.schema", "validate_alerts_frame"),
    "validate_crypto_frame": ("tradinglab_data.schema", "validate_crypto_frame"),
    "validate_daily_frame": ("tradinglab_data.schema", "validate_daily_frame"),
    "validate_fx_daily_frame": ("tradinglab_data.schema", "validate_fx_daily_frame"),
    "validate_fx_pair": ("tradinglab_data.fx", "validate_fx_pair"),
    "validate_intraday_frame": ("tradinglab_data.schema", "validate_intraday_frame"),
    "validate_intraday_live_frame": ("tradinglab_data.schema", "validate_intraday_live_frame"),
    "validate_intraday_research_frame": ("tradinglab_data.schema", "validate_intraday_research_frame"),
    "validate_moves_frame": ("tradinglab_data.schema", "validate_moves_frame"),
    "validate_symbol_master": ("tradinglab_data.symbol_master", "validate_symbol_master"),
    "validate_symbol_master_frame": ("tradinglab_data.schema", "validate_symbol_master_frame"),
}


def __getattr__(name: str) -> Any:
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(name)
    module_name, attr_name = target
    module = import_module(module_name)
    if attr_name is None:
        return module
    return getattr(module, attr_name)


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__) | set(_LAZY_EXPORTS))
